import { readFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { Octokit } from '@octokit/rest';
import type { ChangeEvent, PatchResult, SqliteSnapshotStore } from '@patch-dev/core';
import type { ValidatedPatch } from '@patch-dev/fix';
import {
  describeMissingGithubAuth,
  resolveGithubAuth,
  type GithubAuthResult,
} from './auth.js';
import { prepareAndPushFixBranch } from './push.js';

export {
  resolveGithubAuth,
  describeMissingGithubAuth,
  type GithubAuthResult,
} from './auth.js';
export { prepareAndPushFixBranch } from './push.js';

export interface GithubAppConfig {
  /** GitHub App installation token or PAT. */
  token: string;
  owner: string;
  repo: string;
  confidenceThreshold: number;
  /** Base URL for linking back to the upstream source. */
  sourceUrl?: string;
}

export interface PublishResult {
  kind: 'pr' | 'issue' | 'skipped';
  url?: string;
  number?: number;
  reason?: string;
}

export function renderDescription(params: {
  event: ChangeEvent;
  results: Array<PatchResult & { observability?: ValidatedPatch['observability'] }>;
  sourceUrl?: string;
  asIssue?: boolean;
}): string {
  const { event, results, sourceUrl, asIssue } = params;
  const avgConfidence =
    results.reduce((s, r) => s + r.confidence, 0) / Math.max(results.length, 1);

  const observabilityNotes = results.flatMap((r) => {
    if (!r.observability) return [];
    const o = r.observability;
    return [
      `- \`${r.match_site.file}\`: ${o.attempts} attempt(s)` +
        (o.passedOnAttempt ? `, passed on #${o.passedOnAttempt}` : ', all failed') +
        `, ${o.totalFileReads} file read(s)`,
    ];
  });

  const lines = [
    asIssue
      ? `## Patch diagnosis (below confidence threshold)`
      : `## Patch: upstream API change detected`,
    '',
    `> Generated by [Patch](https://github.com/patchhq/patch). Review carefully before merging.`,
    '',
    '### What changed upstream',
    '',
    `- **Type:** \`${event.type}\``,
    `- **Surface:** \`${event.surface.kind}\` \`${event.surface.path}\``,
    `- **Before:** \`${event.old.signature}\``,
    `- **After:** \`${event.new.signature}\``,
    '',
    event.source_excerpt ? `\`\`\`\n${event.source_excerpt.slice(0, 600)}\n\`\`\`` : '',
    '',
    '### What changed in code',
    '',
    ...results.map(
      (r, i) =>
        `${i + 1}. \`${r.match_site.file}:${r.match_site.line}\` — confidence **${(r.confidence * 100).toFixed(0)}%**\n   ${r.rationale}`,
    ),
    '',
    observabilityNotes.length
      ? `### Fix loop\n\n${observabilityNotes.join('\n')}\n`
      : '',
    sourceUrl ? `### Source\n\n${sourceUrl}\n` : '',
    `### Confidence\n\n**${(avgConfidence * 100).toFixed(0)}%** (threshold-gated)\n`,
    '---',
    '',
    '_This change was generated automatically and should be reviewed by a human._',
  ];

  return lines.join('\n');
}

/**
 * Open a PR when confidence ≥ threshold, otherwise open an Issue.
 * Deduplicates via SnapshotStore change_event_links.
 *
 * App / token permissions: contents (write), pull requests (write), issues (write), metadata (read).
 */
export async function publishResults(params: {
  event: ChangeEvent;
  results: ValidatedPatch[];
  config: GithubAppConfig;
  store: SqliteSnapshotStore;
  /** Absolute path to the consumer repo (used to push a fix branch). */
  repoRoot: string;
  headBranch?: string;
  baseBranch?: string;
}): Promise<PublishResult> {
  const { event, results, config, store } = params;

  const existing = store.getChangeEventLink(event.id);
  if (existing) {
    return { kind: 'skipped', url: existing.github_url, reason: 'already published' };
  }

  if (!config.token) {
    return { kind: 'skipped', reason: describeMissingGithubAuth() };
  }

  const octokit = new Octokit({ auth: config.token });
  const avgConfidence =
    results.reduce((s, r) => s + r.confidence, 0) / Math.max(results.length, 1);
  const above = avgConfidence >= config.confidenceThreshold;
  const body = renderDescription({
    event,
    results,
    sourceUrl: config.sourceUrl,
    asIssue: !above,
  });

  if (above) {
    const branchName =
      params.headBranch ?? `patch/${event.id.slice(0, 8)}`;
    const pushed = prepareAndPushFixBranch({
      repoRoot: params.repoRoot,
      results,
      token: config.token,
      owner: config.owner,
      repo: config.repo,
      branchName,
      baseBranch: params.baseBranch,
    });

    if ('error' in pushed) {
      // Fall back to Issue so the diagnosis is not lost
      const issue = await octokit.issues.create({
        owner: config.owner,
        repo: config.repo,
        title: `patch: fix ready but branch push failed — ${event.surface.path}`,
        body: `${body}\n\n### Push error\n\n\`\`\`\n${pushed.error}\n\`\`\`\n`,
        labels: ['patch', 'needs-review'],
      });
      store.putChangeEventLink(event.id, issue.data.html_url, 'issue');
      return {
        kind: 'issue',
        url: issue.data.html_url,
        number: issue.data.number,
        reason: pushed.error,
      };
    }

    const title = `fix(${event.connector_id}): ${event.type} ${event.surface.path}`;
    const pr = await octokit.pulls.create({
      owner: config.owner,
      repo: config.repo,
      title,
      head: pushed.branchName,
      base: params.baseBranch ?? 'main',
      body,
    });
    store.putChangeEventLink(event.id, pr.data.html_url, 'pr');
    return { kind: 'pr', url: pr.data.html_url, number: pr.data.number };
  }

  const issue = await octokit.issues.create({
    owner: config.owner,
    repo: config.repo,
    title: `patch: possible breaking change in ${event.surface.path}`,
    body,
    labels: ['patch', 'needs-review'],
  });
  store.putChangeEventLink(event.id, issue.data.html_url, 'issue');
  return { kind: 'issue', url: issue.data.html_url, number: issue.data.number };
}

/** Resolve owner/repo from `git remote get-url origin` or env. */
export function resolveRepoSlug(cwd: string): { owner: string; repo: string } | null {
  if (process.env['GITHUB_REPOSITORY']) {
    const [owner, repo] = process.env['GITHUB_REPOSITORY'].split('/');
    if (owner && repo) return { owner, repo };
  }

  const result = spawnSync('git', ['remote', 'get-url', 'origin'], {
    cwd,
    encoding: 'utf8',
  });
  if (result.status !== 0) return null;
  const url = result.stdout.trim();
  const m = /github\.com[:/](?<owner>[^/]+)\/(?<repo>[^/.]+)/.exec(url);
  if (m?.groups?.['owner'] && m.groups['repo']) {
    return { owner: m.groups['owner'], repo: m.groups['repo'] };
  }
  return null;
}

export function readGithubAppInstallUrl(): string {
  return (
    process.env['PATCH_GITHUB_APP_INSTALL_URL'] ??
    'https://github.com/apps/patch-bot/installations/new'
  );
}

/** Dry-run writer for local scans without GitHub credentials. */
export function writeLocalReport(
  cwd: string,
  event: ChangeEvent,
  results: PatchResult[],
): string {
  const dir = join(cwd, '.patch', 'reports');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, `${event.id}.md`);
  writeFileSync(path, renderDescription({ event, results, asIssue: true }), 'utf8');
  return path;
}

export function fileExists(path: string): boolean {
  return existsSync(path);
}

export function readText(path: string): string {
  return readFileSync(path, 'utf8');
}
